on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: canastro/copy-file-action@0.0.2
        name: copy local_conf.h
        with:
          source: "local_config.dist.h"
          target: "local_config.h"
      - uses: arduino/compile-sketches@v1.0.1
        with:
          fqbn: "esp8266:esp8266:nodemcu https://arduino.esp8266.com/stable/package_esp8266com_index.json"
          sketch-paths: |
            - ./
          libraries: |
            # no libraries required
            - name: LEDMatrixDriver
              version: 0.2.2
            - name: PubSubClient
              version: 2.8.0
            - name: WiFiManager
              version: 2.0.12-beta


