on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: canastro/copy-file-action@0.0.2
        name: copy local_config.h
        with:
          source: "local_config.dist.h"
          target: "local_config.h"
      - uses: arduino/compile-sketches@v1.0.1
        name: Compile Sketch
        with:
          fqbn: "esp8266:esp8266:nodemcu https://arduino.esp8266.com/stable/package_esp8266com_index.json"
          sketch-paths: |
            - ./
          libraries: |
            # no libraries required
            - name: LEDMatrixDriver
              version: 0.2.2
            - name: PubSubClient
              version: 2.8.0
            - name: WiFiManager
              version: 2.0.12-beta
      - uses: arduino/report-size-deltas@v1.0.0
        name: Generate size report
