on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
          libraries: |
            # no libraries required
            - name: LEDMatrixDriver
              version: 0.2.2
            - name: PubSubClient
              version: 2.8.0
            - name: WiFiManager
              version: 2.0.12-beta
