on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
  build_release_binaries:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #  board: ["nodemcu", "d1_mini"]
        board: ["d1_mini"]
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: canastro/copy-file-action@0.0.2
        name: copy local_config.h
        with:
          source: "local_config.dist.h"
          target: "local_config.h"
      - uses: arduino/compile-sketches@v1.0.1
        name: Compile Sketch
        with:
          cli-compile-flags: |
            - --output-dir
            - "${{ matrix.board }}"
            - -v
          fqbn: "esp8266:esp8266:${{ matrix.board }} https://arduino.esp8266.com/stable/package_esp8266com_index.json"
          sketch-paths: |
            - ./
          libraries: |
            # no libraries required
            - name: LEDMatrixDriver
              version: 0.2.2
            - name: PubSubClient
              version: 2.8.0
            - name: WiFiManager
              version: 2.0.12-beta
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: "${{ matrix.board }}/MarQueTT.ino.bin"
          asset_name: "marquettino-${{ matrix.board }}-${{ github.ref_name }}.bin"
          asset_content_type: binary/octet-stream

